DOCUMENTS = [
    "Neural networks are computational models inspired by the human brain.",
    "Backpropagation is the algorithm used to train neural networks by computing gradients.",
    "Gradient descent optimizes model parameters by moving in the direction of steepest descent.",
    "Overfitting occurs when a model learns the training data too well and fails to generalize.",
    "Regularization techniques like L1 and L2 help prevent overfitting in machine learning models.",
    "Dropout is a regularization technique that randomly deactivates neurons during training.",
    "Convolutional neural networks are designed for processing grid-like data such as images.",
    "Pooling layers in CNNs reduce spatial dimensions while retaining important features.",
    "Recurrent neural networks process sequential data by maintaining a hidden state.",
    "Long short-term memory networks solve the vanishing gradient problem in RNNs.",
    "Transformers use self-attention mechanisms to process sequences in parallel.",
    "The attention mechanism allows models to focus on relevant parts of the input.",
    "BERT is a transformer model pretrained on masked language modeling and next sentence prediction.",
    "GPT models are autoregressive transformers trained to predict the next token.",
    "Transfer learning allows models pretrained on large datasets to be fine-tuned on specific tasks.",
    "Embeddings are dense vector representations of data in a continuous vector space.",
    "Word2Vec learns word embeddings by predicting surrounding words in a context window.",
    "Sentence transformers produce fixed-size embeddings for entire sentences.",
    "Cosine similarity measures the angle between two vectors regardless of their magnitude.",
    "Dot product similarity is faster than cosine similarity but sensitive to vector magnitude.",
    "FAISS is a library for efficient similarity search over large collections of vectors.",
    "Approximate nearest neighbor search trades accuracy for speed in high-dimensional spaces.",
    "BM25 is a probabilistic ranking function used in information retrieval.",
    "TF-IDF measures how important a word is to a document relative to a corpus.",
    "Hybrid search combines dense vector search with sparse keyword search for better results.",
    "Retrieval-augmented generation grounds LLM responses in retrieved documents.",
    "Chunking splits documents into smaller pieces before embedding for better retrieval granularity.",
    "Chunk overlap ensures context is not lost at the boundaries between chunks.",
    "Vector databases store and index embeddings for fast similarity search at scale.",
    "Reranking reorders retrieved documents using a more powerful cross-encoder model.",
    "Cross-encoders process query and document together for more accurate relevance scoring.",
    "Bi-encoders encode query and document separately enabling fast approximate search.",
    "The curse of dimensionality makes distance metrics less meaningful in high dimensions.",
    "Principal component analysis reduces dimensionality by projecting onto principal components.",
    "K-means clustering partitions data into k clusters by minimizing within-cluster variance.",
    "Random forests combine multiple decision trees to reduce variance and improve accuracy.",
    "Gradient boosting builds an ensemble of weak learners sequentially to minimize loss.",
    "Support vector machines find the hyperplane that maximizes margin between classes.",
    "Logistic regression models the probability of a binary outcome using a sigmoid function.",
    "Precision measures the fraction of retrieved documents that are relevant.",
    "Recall measures the fraction of relevant documents that are retrieved.",
    "F1 score is the harmonic mean of precision and recall.",
    "Mean reciprocal rank measures ranking quality by the position of the first relevant result.",
    "NDCG measures ranking quality taking into account the position of all relevant results.",
    "Data augmentation artificially increases training set size through transformations.",
    "Batch normalization normalizes layer inputs to stabilize and speed up training.",
    "Learning rate scheduling adjusts the learning rate during training for better convergence.",
    "Early stopping halts training when validation loss stops improving to prevent overfitting.",
    "Hyperparameter tuning searches for the optimal configuration of model parameters.",
    "Cross-validation estimates model performance by training and evaluating on multiple data splits.",
]